// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.Commands")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces", Scope = "type", Target = "Microsoft.VisualStudio.Patterning.Authoring.Toolkit.Design")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "Microsoft.VisualStudio.Patterning.Authoring.Toolkit.IAutomationCollection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", MessageId = "GrandChild", Scope = "resource", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.Properties.Resources.resources")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.Conditions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.UriProviders")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.ValueProviders")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Microsoft.VisualStudio.Patterning.Authoring.Toolkit.Automation.Commands")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces", Scope = "type", Target = "Microsoft.VisualStudio.Patterning.Authoring.Authoring.Design")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "Microsoft.VisualStudio.Patterning.Authoring.Authoring.IAutomationCollection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.Commands.AddViewCommand.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.ValueProviders.AutomationLibraryProjectNameValueProvider.#tracer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Event", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Library.IEvents.#Event")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Toolkit.Automation.Commands.CreateAutomationLibraryExtensionCommand.#tracer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Toolkit.Automation.Commands.TailorExistingPatternCommand.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Toolkit.Automation.Commands.TailorExistingPatternCommand.#tracer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Toolkit.Automation.Commands.CreateAutomationLibraryExtensionCommand.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1307:SpecifyStringComparison", MessageId = "System.String.EndsWith(System.String)", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.GuidanceDocumentHelper.#GetDocumentPath(Microsoft.VisualStudio.TeamArchitect.PowerTools.Features.Diagnostics.ITraceSource,Microsoft.VisualStudio.Patterning.Runtime.IProductElement,Microsoft.VisualStudio.TeamArchitect.PowerTools.IFxrUriReferenceService)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.Commands.CreateGuidanceDocumentsCommand.#CleanupGeneratedDocuments(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.Commands.CreateGuidanceDocumentsCommand.#SyncGeneratedProjectFiles(System.Collections.Generic.IDictionary`2<System.String,System.String>,System.String,Microsoft.VisualStudio.TeamArchitect.PowerTools.IItemContainer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.Commands.CreateGuidanceDocumentsCommand.#SyncGeneratedProjectFiles(System.Collections.Generic.IDictionary`2<System.String,System.String>,System.String,Microsoft.VisualStudio.TeamArchitect.PowerTools.IItemContainer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.Commands.ValidatePatternModelCommand.#tracer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1307:SpecifyStringComparison", MessageId = "System.String.EndsWith(System.String)", Scope = "member", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.Commands.CreateGuidanceDocumentsCommand.#GetProjectReference()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Microsoft.VisualStudio.Patterning.Authoring.Automation.ValidationRules")]
