using System;
using Microsoft.VisualStudio.TeamArchitect.PowerTools;

namespace NuPattern.Runtime
{
    /// <summary>
    /// Defines a filter for the picker control.
    /// </summary>
    [CLSCompliant(false)]
    public interface IPickerFilter
    {
        /// <summary>
        /// Whether to apply the fileter or not.
        /// </summary>
        bool ApplyFilter(IItemContainer item);

        /// <summary>
        /// Whether to include containers that do not contain any filtered items.
        /// </summary>
        bool IncludeEmptyContainers { get; set; }

        /// <summary>
        /// Whether to include  the file names of the filtered items.
        /// </summary>
        string IncludeFileExtensions { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether include files generated by t4.
		/// </summary>
		/// <value>
		/// Returns <c>true</c> if include generated files; otherwise, <c>false</c>.
		/// </value>
		bool IncludeGeneratedCode { get; set; }

        /// <summary>
        /// The kinds of itmes to show in the picker.
        /// </summary>
        ItemKind Kind { get; set; }
    }
}