//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Patterning.Authoring.Authoring.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Patterning.Authoring.Authoring.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to synchronize targets files..
        /// </summary>
        internal static string AuthoringPackage_FailedSyncTargets {
            get {
                return ResourceManager.GetString("AuthoringPackage_FailedSyncTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing Targets.
        /// </summary>
        internal static string AuthoringPackage_TraceSyncTargetsInitial {
            get {
                return ResourceManager.GetString("AuthoringPackage_TraceSyncTargetsInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of current targets file &apos;{0}&apos; not found, aborting update..
        /// </summary>
        internal static string AuthoringPackage_TraceSyncTargetsNoVersion {
            get {
                return ResourceManager.GetString("AuthoringPackage_TraceSyncTargetsNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets file &apos;{0}&apos; matches current version (&apos;{1}&apos;), update skipped..
        /// </summary>
        internal static string AuthoringPackage_TraceSyncTargetsNoVersionUpdate {
            get {
                return ResourceManager.GetString("AuthoringPackage_TraceSyncTargetsNoVersionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving version from targets file at &apos;{0}&apos;..
        /// </summary>
        internal static string AuthoringPackage_TraceSyncTargetsRetrievingVersion {
            get {
                return ResourceManager.GetString("AuthoringPackage_TraceSyncTargetsRetrievingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing targets file &apos;{0}&apos; requires updating from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string AuthoringPackage_TraceSyncTargetsUpdateVersion {
            get {
                return ResourceManager.GetString("AuthoringPackage_TraceSyncTargetsUpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating new targets file &apos;{0}&apos; to version &apos;{1}&apos;..
        /// </summary>
        internal static string AuthoringPackage_TraceSyncTargetsWritingNewTargets {
            get {
                return ResourceManager.GetString("AuthoringPackage_TraceSyncTargetsWritingNewTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Toolkit Hands-On Labs.
        /// </summary>
        internal static string InstantiateHolLink_InstanceName {
            get {
                return ResourceManager.GetString("InstantiateHolLink_InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Pattern Toolkit Hands-On Labs&apos; toolkit is not installed. You must install the toolkit first..
        /// </summary>
        internal static string InstantiateHolLink_WarningNotInstalled {
            get {
                return ResourceManager.GetString("InstantiateHolLink_WarningNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Toolkit Builder.
        /// </summary>
        internal static string InstantiateHolLink_WarningTitle {
            get {
                return ResourceManager.GetString("InstantiateHolLink_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_VisualStudio_Patterning_Authoring_PatternToolkitVersion {
            get {
                object obj = ResourceManager.GetObject("Microsoft_VisualStudio_Patterning_Authoring_PatternToolkitVersion", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
