//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace NuPattern.Runtime.Schema
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public abstract partial class PatternModelSchemaBase
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidatePatternModelSchemaBaseMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Pattern == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						NuPattern.Runtime.Schema.PatternModelDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"PatternModelSchema", "", "Pattern"),
						"DSL0001", this);
			}
		} // ValidatePatternModelSchemaBaseMultiplicity
	} // class PatternModelSchemaBase
} // NuPattern.Runtime.Schema

namespace NuPattern.Runtime.Schema
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class PatternSchema
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidatePatternSchemaMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Views.Count == 0)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						NuPattern.Runtime.Schema.PatternModelDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"PatternSchema", this.Name, "Views"),
						"DSL0001", this);
			}
		} // ValidatePatternSchemaMultiplicity
	} // class PatternSchema
} // NuPattern.Runtime.Schema

namespace NuPattern.Runtime.Schema
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public abstract partial class CustomizableElementSchemaBase
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateCustomizableElementSchemaBaseMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Policy == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						NuPattern.Runtime.Schema.PatternModelDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"CustomizableElementSchema", this.Name, "Policy"),
						"DSL0001", this);
			}
		} // ValidateCustomizableElementSchemaBaseMultiplicity
	} // class CustomizableElementSchemaBase
} // NuPattern.Runtime.Schema

	
 