// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.DialogBoxPurger.#.ctor(System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.DialogBoxPurger.#.ctor(System.Int32,System.Int32,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.DialogBoxPurger.#.ctor(System.Int32,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1304:SpecifyCultureInfo", MessageId = "System.String.ToLower", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.DialogBoxPurger.#FindMessageBoxString(System.IntPtr,System.IntPtr)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "serviceProvider", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.DialogBoxPurger.#Start()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "uiShell", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.DialogBoxPurger.#Start()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "threadDone", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.DialogBoxPurger.#System.IDisposable.Dispose()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2213:DisposableFieldsShouldBeDisposed", MessageId = "threadStarted", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.DialogBoxPurger.#System.IDisposable.Dispose()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#AttachThreadInput(System.UInt32,System.UInt32,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Interoperability", "CA1414:MarkBooleanPInvokeArgumentsWithMarshalAs", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#AttachThreadInput(System.UInt32,System.UInt32,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#DispatchMessage(Microsoft.VisualStudio.OLE.Interop.MSG&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", MessageId = "return", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#DispatchMessage(Microsoft.VisualStudio.OLE.Interop.MSG&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Interoperability", "CA1414:MarkBooleanPInvokeArgumentsWithMarshalAs", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#EndDialog(System.IntPtr,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", MessageId = "1", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#EndDialog(System.IntPtr,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA2101:SpecifyMarshalingForPInvokeStringArguments", MessageId = "1", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#GetClassName(System.IntPtr,System.Text.StringBuilder,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#GetCurrentThreadId()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#GetLastError()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2205:UseManagedEquivalentsOfWin32Api", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#GetLastError()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA2101:SpecifyMarshalingForPInvokeStringArguments", MessageId = "1", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#GetWindowText(System.IntPtr,System.Text.StringBuilder,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#GetWindowThreadProcessId(System.IntPtr,System.UInt32&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#HResultFromWin32(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#IsSamePath(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#IsWindowVisible(System.IntPtr)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Interoperability", "CA1414:MarkBooleanPInvokeArgumentsWithMarshalAs", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#IsWindowVisible(System.IntPtr)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#PeekMessage(Microsoft.VisualStudio.OLE.Interop.MSG&,System.Runtime.InteropServices.HandleRef,System.Int32,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", MessageId = "2", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#SendMessage(System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", MessageId = "return", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#SendMessage(System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#SetFocus(System.IntPtr)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#TranslateMessage(Microsoft.VisualStudio.OLE.Interop.MSG&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Interoperability", "CA1414:MarkBooleanPInvokeArgumentsWithMarshalAs", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#TranslateMessage(Microsoft.VisualStudio.OLE.Interop.MSG&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Interoperability", "CA1414:MarkBooleanPInvokeArgumentsWithMarshalAs", Scope = "member", Target = "Microsoft.VsSDK.IntegrationTestLibrary.NativeMethods.#PeekMessage(Microsoft.VisualStudio.OLE.Interop.MSG&,System.Runtime.InteropServices.HandleRef,System.Int32,System.Int32,System.Int32)")]
