//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuPattern.Extensibility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuPattern.Extensibility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found &apos;{0}&apos; distinct referenced assemblies from all projects in the solution..
        /// </summary>
        internal static string AssemblyDiscoveryService_GetAssemblies_TraceAssembliesFound {
            get {
                return ResourceManager.GetString("AssemblyDiscoveryService_GetAssemblies_TraceAssembliesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching referenced assemblies from all projects in the solution.
        /// </summary>
        internal static string AssemblyDiscoveryService_GetAssemblies_TraceInitial {
            get {
                return ResourceManager.GetString("AssemblyDiscoveryService_GetAssemblies_TraceInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution could not be opened.
        /// </summary>
        internal static string AssemblyDiscoveryService_GetAssemblies_TraceNoSolution {
            get {
                return ResourceManager.GetString("AssemblyDiscoveryService_GetAssemblies_TraceNoSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the Visual Studio default catalog and the Feature Builder catalogs must be present in the system..
        /// </summary>
        internal static string BindingCompositionService_CatalogsNotAvailable {
            get {
                return ResourceManager.GetString("BindingCompositionService_CatalogsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize root binding composition service..
        /// </summary>
        internal static string BindingCompositionService_FailedToInitialize {
            get {
                return ResourceManager.GetString("BindingCompositionService_FailedToInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default implementation of the IFeatureCompositionService changed and no longer contains the expected composition container named &apos;container&apos;..
        /// </summary>
        internal static string BindingFactory_DefaultCompositionServiceChanged {
            get {
                return ResourceManager.GetString("BindingFactory_DefaultCompositionServiceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve a valid composition container instance from the &apos;container&apos; field in the default implementation of the IFeatureCompositionService..
        /// </summary>
        internal static string BindingFactory_DefaultCompositionServiceContainerUnavailable {
            get {
                return ResourceManager.GetString("BindingFactory_DefaultCompositionServiceContainerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding composition service does not expose an ExportProvider or a CompositionContainer, so dynamic context values cannot be supported..
        /// </summary>
        internal static string BindingFactory_DynamicContextUnsupported {
            get {
                return ResourceManager.GetString("BindingFactory_DynamicContextUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic evaluation context was not created by this binding..
        /// </summary>
        internal static string BindingFactory_UnsupportedDynamicContext {
            get {
                return ResourceManager.GetString("BindingFactory_UnsupportedDynamicContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize to an instance of {0} the serialized value: {1}.
        /// </summary>
        internal static string BindingSerializationException_DeserializationFailed {
            get {
                return ResourceManager.GetString("BindingSerializationException_DeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the component. Once selected, the specific properties of the selected component can be configured..
        /// </summary>
        internal static string BindingSettings_TypeIdDescription {
            get {
                return ResourceManager.GetString("BindingSettings_TypeIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string BindingSettings_TypeIdDisplayName {
            get {
                return ResourceManager.GetString("BindingSettings_TypeIdDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap files(*.bmp)|*.bmp.
        /// </summary>
        internal static string BitmapFilter {
            get {
                return ResourceManager.GetString("BitmapFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization has already been done. This invocation can only be performed before EndInit is been called..
        /// </summary>
        internal static string CodeGeneration_InitializationFinished {
            get {
                return ResourceManager.GetString("CodeGeneration_InitializationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization has not been finished yet. This invocation can only be performed after EndInit has been called..
        /// </summary>
        internal static string CodeGeneration_InitializationPending {
            get {
                return ResourceManager.GetString("CodeGeneration_InitializationPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The associated converter does not support standard values..
        /// </summary>
        internal static string CollectionDropDownEditor_ConverterException {
            get {
                return ResourceManager.GetString("CollectionDropDownEditor_ConverterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must implement ICollection..
        /// </summary>
        internal static string CollectionDropDownEditor_ValueCollectionException {
            get {
                return ResourceManager.GetString("CollectionDropDownEditor_ValueCollectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Collection).
        /// </summary>
        internal static string CollectionPropertyDescriptor_ToString {
            get {
                return ResourceManager.GetString("CollectionPropertyDescriptor_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Condition Binding).
        /// </summary>
        internal static string ConditionBindingSettings_ElementName {
            get {
                return ResourceManager.GetString("ConditionBindingSettings_ElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to dispose wizard extension &apos;{0}&apos;..
        /// </summary>
        internal static string CoordinatorTemplateWizard_FailedToDispose {
            get {
                return ResourceManager.GetString("CoordinatorTemplateWizard_FailedToDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured assembly &apos;{0}&apos; could not be loaded..
        /// </summary>
        internal static string CoordinatorTemplateWizard_FailedToLoadAssembly {
            get {
                return ResourceManager.GetString("CoordinatorTemplateWizard_FailedToLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured type &apos;{0}&apos; was not found in assembly &apos;{1}&apos;..
        /// </summary>
        internal static string CoordinatorTemplateWizard_FailedToLoadType {
            get {
                return ResourceManager.GetString("CoordinatorTemplateWizard_FailedToLoadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading wizard type &apos;{0}, {1}&apos;..
        /// </summary>
        internal static string CoordinatorTemplateWizard_LoadingWizardType {
            get {
                return ResourceManager.GetString("CoordinatorTemplateWizard_LoadingWizardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured wizard type &apos;{0}&apos; does not implement required interface &apos;{1}&apos;..
        /// </summary>
        internal static string CoordinatorTemplateWizard_NotIWizard {
            get {
                return ResourceManager.GetString("CoordinatorTemplateWizard_NotIWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template wizard unexpectedly failed..
        /// </summary>
        internal static string CoordinatorTemplateWizard_TryFailed {
            get {
                return ResourceManager.GetString("CoordinatorTemplateWizard_TryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find or create target path &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotFindOrCreate {
            get {
                return ResourceManager.GetString("CouldNotFindOrCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string DefaultCategory {
            get {
                return ResourceManager.GetString("DefaultCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The descriptor must inherit from {0} or provide a constructor receiving a single parameter of type {1}, which is the original one to be replaced..
        /// </summary>
        internal static string DescriptorExtensions_MustBeDelegatingDescriptor {
            get {
                return ResourceManager.GetString("DescriptorExtensions_MustBeDelegatingDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (provided by: &apos;{0}&apos;).
        /// </summary>
        internal static string DesignProperty_ToStringValueProviderFormat {
            get {
                return ResourceManager.GetString("DesignProperty_ToStringValueProviderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;Value Provider&apos; that provides a value for this property at runtime. If a &apos;Value&apos; is also defined then the &apos;Value Provider&apos; property is ignored..
        /// </summary>
        internal static string DesignProperty_ValueProviderDescription {
            get {
                return ResourceManager.GetString("DesignProperty_ValueProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Provider.
        /// </summary>
        internal static string DesignProperty_ValueProviderDisplayName {
            get {
                return ResourceManager.GetString("DesignProperty_ValueProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configured value for this property, defined at design-time..
        /// </summary>
        internal static string DesignPropertyValueDescriptor_ValueDescription {
            get {
                return ResourceManager.GetString("DesignPropertyValueDescriptor_ValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string DesignPropertyValueDescriptor_ValueDisplayName {
            get {
                return ResourceManager.GetString("DesignPropertyValueDescriptor_ValueDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new empty solution, an error occurred creating and saving the new solution to &apos;{0}&apos;. Verify that you have permissions to create new subfolders in the parent directory..
        /// </summary>
        internal static string DteExtensions_CreateNewSolution_FailedCreate {
            get {
                return ResourceManager.GetString("DteExtensions_CreateNewSolution_FailedCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new empty solution, the default save location for new solutions could not be found..
        /// </summary>
        internal static string DteExtensions_CreateNewSolution_FailedDirSearch {
            get {
                return ResourceManager.GetString("DteExtensions_CreateNewSolution_FailedDirSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic context creation is only available for bindings created using the BindingFactory..
        /// </summary>
        internal static string DynamicBinding_UnsupportedCompositionService {
            get {
                return ResourceManager.GetString("DynamicBinding_UnsupportedCompositionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain class {0} doesn&apos;t have a Name domain property.
        /// </summary>
        internal static string ElementNameNotSupported {
            get {
                return ResourceManager.GetString("ElementNameNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string FeatureExtensionsTypeConverter_None {
            get {
                return ResourceManager.GetString("FeatureExtensionsTypeConverter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new instance of the guidance workflow &apos;{0} ({1})&apos;. .
        /// </summary>
        internal static string FeatureManagerExtensions_ErrorGuidanceInstantiationFailed {
            get {
                return ResourceManager.GetString("FeatureManagerExtensions_ErrorGuidanceInstantiationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to activate an instance of the feature extension &apos;{0}&apos;. It is not installed..
        /// </summary>
        internal static string FeatureManagerExtensions_ErrorNoRegistration {
            get {
                return ResourceManager.GetString("FeatureManagerExtensions_ErrorNoRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating guidance workflow &apos;{0}&apos;.
        /// </summary>
        internal static string FeatureManagerExtensions_TraceActivation {
            get {
                return ResourceManager.GetString("FeatureManagerExtensions_TraceActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing guidance windows.
        /// </summary>
        internal static string FeatureManagerExtensions_TraceShowingGuidanceWindows {
            get {
                return ResourceManager.GetString("FeatureManagerExtensions_TraceShowingGuidanceWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder path &apos;{0}&apos; already exists..
        /// </summary>
        internal static string FolderPathAlreadyExists {
            get {
                return ResourceManager.GetString("FolderPathAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A guidance workflow associated to the current element..
        /// </summary>
        internal static string GuidanceReference_Description {
            get {
                return ResourceManager.GetString("GuidanceReference_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance Link.
        /// </summary>
        internal static string GuidanceReference_DisplayName {
            get {
                return ResourceManager.GetString("GuidanceReference_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon files(*.ico)|*.ico.
        /// </summary>
        internal static string IconFilter {
            get {
                return ResourceManager.GetString("IconFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files(*.gif;*.jpg;*.jpeg;*.bmp;*.png)|*.gif;*.jpg;*.jpeg;*.bmp;*.png.
        /// </summary>
        internal static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no image files ({0}) found in the current solution.
        ///Please add a new or existing image file {0} to the project and try again..
        /// </summary>
        internal static string ImageUriEditor_EmptyItemsMessage {
            get {
                return ResourceManager.GetString("ImageUriEditor_EmptyItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to edit file..
        /// </summary>
        internal static string ImageUriEditor_FailedToEdit {
            get {
                return ResourceManager.GetString("ImageUriEditor_FailedToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Image from the Solution.
        /// </summary>
        internal static string ImageUriEditor_PickerTitle {
            get {
                return ResourceManager.GetString("ImageUriEditor_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to create can only be relative to a solution, solution folder, project or folder. Invalid relative node kind &apos;{0}&apos; found at &apos;{1}&apos; for path expression &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidFolderPath {
            get {
                return ResourceManager.GetString("InvalidFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution element &apos;{0}&apos; must be contained in a project in the solution..
        /// </summary>
        internal static string IProjectExtensions_ItemNotInProject {
            get {
                return ResourceManager.GetString("IProjectExtensions_ItemNotInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The solution element &apos;{0}&apos; must be contained in a project containing a VSIX manifest file marked with the &apos;{1}&apos; MSBuild metadata..
        /// </summary>
        internal static string IProjectExtensions_NotToolkitProject {
            get {
                return ResourceManager.GetString("IProjectExtensions_NotToolkitProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name expression &apos;{0}&apos; evaluated to a null or empty string, which is invalid. This may be caused by a reference to a non-existent property or a property that has a null or empty value..
        /// </summary>
        internal static string PathResolver_ErrorFileNameEvaluatedEmpty {
            get {
                return ResourceManager.GetString("PathResolver_ErrorFileNameEvaluatedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact link &apos;{0}&apos; on element &apos;{1}&apos; could not be resolved to a solution artifact..
        /// </summary>
        internal static string PathResolver_ErrorInvalidArtifactLink {
            get {
                return ResourceManager.GetString("PathResolver_ErrorInvalidArtifactLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve a solution artifact from the current element &apos;{0}&apos; or any of its ancestors. Element relative path &apos;{1}&apos; cannot be resolved..
        /// </summary>
        internal static string PathResolver_ErrorNoAncestorWithArtifactLink {
            get {
                return ResourceManager.GetString("PathResolver_ErrorNoAncestorWithArtifactLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &apos;{0}&apos; specifies a product store relative path that resolved to element &apos;{1}&apos;, but the element does not contain an artifact link..
        /// </summary>
        internal static string PathResolver_ErrorNoArtifactLinkOnParent {
            get {
                return ResourceManager.GetString("PathResolver_ErrorNoArtifactLinkOnParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &apos;{0}&apos; specifies an explicit product relative path that could not be resolved to a valid parent or ancestor element..
        /// </summary>
        internal static string PathResolver_ErrorNoParentFound {
            get {
                return ResourceManager.GetString("PathResolver_ErrorNoParentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path expression &apos;{0}&apos; evaluated to a null or empty string, which is invalid. This may be caused by a reference to a non-existent property or a property that has a null or empty value..
        /// </summary>
        internal static string PathResolver_PathEvaluatedEmpty {
            get {
                return ResourceManager.GetString("PathResolver_PathEvaluatedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated file name &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string PathResolver_TraceEvaluatedFileName {
            get {
                return ResourceManager.GetString("PathResolver_TraceEvaluatedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated path &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string PathResolver_TraceEvaluatedPath {
            get {
                return ResourceManager.GetString("PathResolver_TraceEvaluatedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find solution item references of the element &apos;{0}&apos;.
        /// </summary>
        internal static string PathResolver_TraceInvalidArtifactLink {
            get {
                return ResourceManager.GetString("PathResolver_TraceInvalidArtifactLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find solution item references in the parent element.
        /// </summary>
        internal static string PathResolver_TraceInvalidParentArtifactLink {
            get {
                return ResourceManager.GetString("PathResolver_TraceInvalidParentArtifactLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Resolving &apos;{0}&apos; to element &apos;{1}&apos;.
        /// </summary>
        internal static string PathResolver_TraceLocateParentResolvingElement {
            get {
                return ResourceManager.GetString("PathResolver_TraceLocateParentResolvingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Using solution item relative path &apos;{0}&apos;.
        /// </summary>
        internal static string PathResolver_TraceLocateParentUsingRelativePath {
            get {
                return ResourceManager.GetString("PathResolver_TraceLocateParentUsingRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find solution item references in ancestor elements..
        /// </summary>
        internal static string PathResolver_TraceNoAncestor {
            get {
                return ResourceManager.GetString("PathResolver_TraceNoAncestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find a parent for the element..
        /// </summary>
        internal static string PathResolver_TraceNoParent {
            get {
                return ResourceManager.GetString("PathResolver_TraceNoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Applying expression &apos;{0}&apos; to element &apos;{1}&apos;.
        /// </summary>
        internal static string PathResolver_TraceResolveApplyingExpression {
            get {
                return ResourceManager.GetString("PathResolver_TraceResolveApplyingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved artifact link in path &apos;{0}&apos;, which resolved to &apos;{1}&apos;..
        /// </summary>
        internal static string PathResolver_TraceResolvedArtifactLink {
            get {
                return ResourceManager.GetString("PathResolver_TraceResolvedArtifactLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Evaluated file name to &apos;{0}&apos;.
        /// </summary>
        internal static string PathResolver_TraceResolveEvaluatedFileName2 {
            get {
                return ResourceManager.GetString("PathResolver_TraceResolveEvaluatedFileName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Evaluated path to &apos;{0}&apos;.
        /// </summary>
        internal static string PathResolver_TraceResolveEvaluatedPath {
            get {
                return ResourceManager.GetString("PathResolver_TraceResolveEvaluatedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Couldn&apos;t evaluate expression.
        /// </summary>
        internal static string PathResolver_TraceResolveFailedExpressionEvaluation {
            get {
                return ResourceManager.GetString("PathResolver_TraceResolveFailedExpressionEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving path=&apos;{0}&apos;, filename=&apos;{1}&apos;.
        /// </summary>
        internal static string PathResolver_TraceResolveInitial {
            get {
                return ResourceManager.GetString("PathResolver_TraceResolveInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Path to resolve is null, default to &apos;{0}&apos;.
        /// </summary>
        internal static string PathResolver_TraceResolveLinkInPathDefaulting {
            get {
                return ResourceManager.GetString("PathResolver_TraceResolveLinkInPathDefaulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Resolving for element &apos;{0}&apos;.
        /// </summary>
        internal static string PathResolver_TraceResolveLinkInPathResolvingElement {
            get {
                return ResourceManager.GetString("PathResolver_TraceResolveLinkInPathResolvingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Using references from element &apos;{0}&apos;.
        /// </summary>
        internal static string PathResolver_TraceResolveLinkInPathUsiingElementReference {
            get {
                return ResourceManager.GetString("PathResolver_TraceResolveLinkInPathUsiingElementReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path resolved to &apos;{0}&apos;.
        /// </summary>
        internal static string PathResolver_TraceResolvePath {
            get {
                return ResourceManager.GetString("PathResolver_TraceResolvePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name resolved to &apos;{0}&apos;.
        /// </summary>
        internal static string PathResolver_TraceResolveResolvedFileName {
            get {
                return ResourceManager.GetString("PathResolver_TraceResolveResolvedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see the Output Window (&apos;NuPattern Toolkit Extensions&apos; pane) for more information...
        /// </summary>
        internal static string SeeDiagnosticsWindow {
            get {
                return ResourceManager.GetString("SeeDiagnosticsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bitmap.
        /// </summary>
        internal static string SelectBitmap {
            get {
                return ResourceManager.GetString("SelectBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Icon.
        /// </summary>
        internal static string SelectIcon {
            get {
                return ResourceManager.GetString("SelectIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project, folder or file associated to the current element..
        /// </summary>
        internal static string SolutionArtifactLinkReference_Description {
            get {
                return ResourceManager.GetString("SolutionArtifactLinkReference_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Item Link.
        /// </summary>
        internal static string SolutionArtifactLinkReference_DisplayName {
            get {
                return ResourceManager.GetString("SolutionArtifactLinkReference_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Associated Solution Item.
        /// </summary>
        internal static string SolutionArtifactLinkReference_EditorTitle {
            get {
                return ResourceManager.GetString("SolutionArtifactLinkReference_EditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution item with name &apos;{0}&apos; already exists, rename failed..
        /// </summary>
        internal static string SolutionExtensions_ErrorRenamedItemExists {
            get {
                return ResourceManager.GetString("SolutionExtensions_ErrorRenamedItemExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown  solution item type for rename.
        /// </summary>
        internal static string SolutionExtensions_ErrorRenameUnknownType {
            get {
                return ResourceManager.GetString("SolutionExtensions_ErrorRenameUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; is required..
        /// </summary>
        internal static string SolutionExtensions_MissingService {
            get {
                return ResourceManager.GetString("SolutionExtensions_MissingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An associated solution item (file, folder or project) with the name &apos;{0}&apos; already exists in the solution. 
        ///The solution item has instead been renamed to: &apos;{1}&apos;..
        /// </summary>
        internal static string SolutionExtensions_PromptItemAlreadyExists_Message {
            get {
                return ResourceManager.GetString("SolutionExtensions_PromptItemAlreadyExists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Item Already Exists.
        /// </summary>
        internal static string SolutionExtensions_PromptItemAlreadyExists_Title {
            get {
                return ResourceManager.GetString("SolutionExtensions_PromptItemAlreadyExists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project type is not supported. It must be a Visual Studio project..
        /// </summary>
        internal static string SolutionExtensions_UnsupportedProject {
            get {
                return ResourceManager.GetString("SolutionExtensions_UnsupportedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing existing active scope..
        /// </summary>
        internal static string TemplateWizard_CompletingScope {
            get {
                return ResourceManager.GetString("TemplateWizard_CompletingScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard extension {0} has been disposed..
        /// </summary>
        internal static string TemplateWizard_Disposed {
            get {
                return ResourceManager.GetString("TemplateWizard_Disposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item template &apos;{0}&apos; but no unfolded item(s) were found in the solution..
        /// </summary>
        internal static string TemplateWizard_ItemTemplateNoItem {
            get {
                return ResourceManager.GetString("TemplateWizard_ItemTemplateNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project template &apos;{0}&apos; but no unfolded projects(s) were found in the solution..
        /// </summary>
        internal static string TemplateWizard_ProjectTemplateNoProject {
            get {
                return ResourceManager.GetString("TemplateWizard_ProjectTemplateNoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard extension {0} started processing for template {1}..
        /// </summary>
        internal static string TemplateWizard_Unfolding {
            get {
                return ResourceManager.GetString("TemplateWizard_Unfolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project, folder or file unfolded as part of a template for the current element..
        /// </summary>
        internal static string UnfoldedArtifactLink_Description {
            get {
                return ResourceManager.GetString("UnfoldedArtifactLink_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfolded Artifact Link.
        /// </summary>
        internal static string UnfoldedArtifactLink_DisplayName {
            get {
                return ResourceManager.GetString("UnfoldedArtifactLink_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Validation Rule Binding).
        /// </summary>
        internal static string ValidationBindingSettings_ElementName {
            get {
                return ResourceManager.GetString("ValidationBindingSettings_ElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed for {0}:.
        /// </summary>
        internal static string ValidationException {
            get {
                return ResourceManager.GetString("ValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string ValidationResult {
            get {
                return ResourceManager.GetString("ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; validation failed..
        /// </summary>
        internal static string ValidatorDefaultMessage {
            get {
                return ResourceManager.GetString("ValidatorDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value provider binding for property {0} on element {1} failed to evaluate..
        /// </summary>
        internal static string ValueProviderBinding_FailedToEvaluate {
            get {
                return ResourceManager.GetString("ValueProviderBinding_FailedToEvaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Value Provider Binding).
        /// </summary>
        internal static string ValueProviderBindingSettings_ElementName {
            get {
                return ResourceManager.GetString("ValueProviderBindingSettings_ElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vsix manifest file &apos;{0}&apos; does not contain required Identifier element..
        /// </summary>
        internal static string Vsix_InvalidManifest {
            get {
                return ResourceManager.GetString("Vsix_InvalidManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vsix file &apos;{0}&apos; does not contain the required manifest named &quot;extension.vsixmanifest&quot;..
        /// </summary>
        internal static string Vsix_ManifestMissing {
            get {
                return ResourceManager.GetString("Vsix_ManifestMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML document load failed for file &apos;{0}&apos;..
        /// </summary>
        internal static string XmlProcessor_ErrorLoadFailed {
            get {
                return ResourceManager.GetString("XmlProcessor_ErrorLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML document must be loaded before you can call this method..
        /// </summary>
        internal static string XmlProcessor_ErrorLoadNotCalledFirst {
            get {
                return ResourceManager.GetString("XmlProcessor_ErrorLoadNotCalledFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save modified XML document &apos;{0}&apos;..
        /// </summary>
        internal static string XmlProcessor_ErrorSaveFailed {
            get {
                return ResourceManager.GetString("XmlProcessor_ErrorSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find nodes in the XMLdocument using XPath search &apos;{0}&apos;.
        /// </summary>
        internal static string XmlProcessor_ErrorXPathSearchFailed {
            get {
                return ResourceManager.GetString("XmlProcessor_ErrorXPathSearchFailed", resourceCulture);
            }
        }
    }
}
